//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.LinkingTableForMPBs = new HashSet<LinkingTableForMPB>();
        }
    
        public System.Guid MemberID { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Company { get; set; }
        public string Photo { get; set; }
        public string Bio { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<LinkingTableForMPB> LinkingTableForMPBs { get; set; }
    }
}
