//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.LinkingTableForMPBs = new HashSet<LinkingTableForMPB>();
        }
    
        public System.Guid ProjectID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
        public bool IsActive { get; set; }
        public string ProjectPic { get; set; }
        public System.DateTime DatePublished { get; set; }
    
        public virtual ICollection<LinkingTableForMPB> LinkingTableForMPBs { get; set; }
    }
}
